### ISSUE TITLE
notesの全ての英語サポートをする。

### ISSUE THREAD

**Issue by tasuren** [RT-Team/RT-Team.github.io#4]
`*.md`を`*.en.md`という名前にして英語バージョンを作り、各オリジナルページの最初に「英語バージョンはこちら」と書く。

* [x] `notes/`
  * [x] `color.md`
  * [x] `embed.md`
  * [x] `help.md`
  * [x] `index.md`
  * [x] `slash_tanle.md`
  * [x] `tutorial.md`
  * [x] `what_is_self_bot.md`
* [x] `trouble`
  * [x] `index.md`
  * [x] `role.md`
* [x] `/`
  * [x] `rt_chan.md`
  * [x] `README.md`

**Comment by tuna2134** [comment]
Ok

**Comment by tuna2134** [comment]
https://github.com/tuna2134/RT-Team.github.io/tree/patch-3

**Comment by tuna2134** [comment]
ここで作っている

**Comment by tuna2134** [comment]
もうここ閉じてよくね？

**Comment by tasuren** [comment]
実装した。
